### ISSUE TITLE
Feature Request: OS-specific newline delimiter

### ISSUE THREAD

**Issue by aschlosberg** [palantir/eclipse-typescript#235]
Thanks for a great plugin.

My output .js files appear to be in DOS format with carriage returns in the newlines. Is it possible to utilise the option as specified in: 'General > Workspace > New text file line delimiter'?

For anyone else with this issue, my temporary workaround is to add a Program Builder after the TypeScript Builder and simply call a bash script that modifies the necessary files with dos2unix.

**Comment by derekcicerone** [comment]
Interesting, 2 questions:
1. Are you running this on a Windows machine or Mac/Linux?
2. Does tsc have the same issue? (is there an option to change its output file line endings?)

**Comment by aschlosberg** [comment]
1. Ubuntu 14.04; Eclipse 3.8.1
2. No tsc doesn't have the problem, and as far as I know there is no option to specify it. I tried running tsc as a Program Builder instead of the TypeScript Builder as suggested in the wiki, but ran into too many issues with automatic building.

**Comment by derekcicerone** [comment]
Ok, cool, thanks for the report. Fixing this required using a new API available only in TypeScript 1.5 so the fix is on the develop version of the Eclipse TypeScript plug-in (its tracking 1.5). You can switch to the development version to get the fix now (but TypeScript there is potentially unstable). I expect the full version to be available within a few weeks (its waiting on the public release of TypeScript 1.5).

**Comment by aschlosberg** [comment]
Thanks for the rapid turnaround time.
