### ISSUE TITLE
reference: File not found

### ISSUE THREAD

**Issue by styxxx** [palantir/eclipse-typescript#286]
Hi,

no matter what I try I always get the error message "file not found" when trying to add a reference. The location of the file doesn't matter (parent directory, sub directory or the same). Also how I specify the path doesn't seem to make any difference (with leading "./" or without for example - so it's not the same bug that only affects paths with ".."). 

The file exists and tsc on command line compiles the file without error.

My installation it fresh with the newest plugin version. I also checked file permissions. I'm using Debian testing as OS.

**Comment by derekcicerone** [comment]
Hi, unfortunately there aren't many people actively working on this project currently so it may be a while before we can look into this issue. If you'd like to take a shot at debugging it and submitting a PR, we'd love to have it.

**Comment by brndusic** [comment]
Hi ,

I'm also having this issue, here is a screenshot http://prntscr.com/8svanm . I must change now this eclipse plugin because can't work with it :(

**Comment by brndusic** [comment]
Hi found a problem, my source file were in subfolder and typing definitions were in other subfolder. If you go to typescript folder you and set subfolder as your source folder you will have this problem. So best way to fix the issue is to leave empty source folder field and then your root folder will be used as source folder and all will work.
